"""Remove uniqueconstraint

Revision ID: 342ca557305e
Revises: c6abf243169f
Create Date: 2020-10-01 13:14:22.458023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342ca557305e'
down_revision = 'c6abf243169f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notebooks_title_userId_key', 'notebooks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('notebooks_title_userId_key', 'notebooks', ['title', 'userId'])
    # ### end Alembic commands ###
